date=2023-11-20 15:56:47
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 362, in <lambda>
    self.comboBox_cmd_preset.currentTextChanged.connect(lambda : self.load_preset('cmd'))
  File "D:\R2A\R2A.py", line 990, in load_preset
    df = df.fillna('')
AttributeError: 'NoneType' object has no attribute 'fillna'

date=2023-11-14 11:35:45
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 889, in addCmdPresetBookmark
    getattr(self, f'btn_cmd_preset_bookmark_{target_preset_num}').setText()
TypeError: setText(self, text: str): not enough arguments


────────────────────────────────────────
date=2023-11-14 11:35:43
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 889, in addCmdPresetBookmark
    getattr(self, f'btn_cmd_preset_bookmark_{target_preset_num}').setText()
TypeError: setText(self, text: str): not enough arguments


────────────────────────────────────────
date=2023-11-14 11:35:39
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 889, in addCmdPresetBookmark
    getattr(self, f'btn_cmd_preset_bookmark_{target_preset_num}').setText()
TypeError: setText(self, text: str): not enough arguments


────────────────────────────────────────
date=2023-11-14 11:34:55
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 889, in addCmdPresetBookmark
    getattr(self, f'btn_cmd_preset_bookmark_{target_preset_num}').setText()
TypeError: setText(self, text: str): not enough arguments


        date=2023-11-01 11:39:58
        user=mssung
        Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 1018, in executeMultiCommand
    headerText = self.input_cmd_header.text()
AttributeError: 'WindowClass' object has no attribute 'input_cmd_header'

    date=2023-11-01 11:40:28
    user=mssung
        Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 1018, in executeMultiCommand
    headerText = self.input_cmd_header.text()
AttributeError: 'WindowClass' object has no attribute 'input_cmd_header'

    date=2023-11-01 11:41:45
    user=mssung
        Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 649, in 파일열기
    os.startfile(filePath)
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다: 'None'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 652, in 파일열기
    os.startfile(os.path.abspath(filePath))
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다: 'D:\\R2A\\None'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 390, in <lambda>
    getattr(self, f'btn_findData_openFile_{i}').clicked.connect(lambda _, x=i : self.데이터파일열기(x))
  File "D:\R2A\R2A.py", line 1199, in 데이터파일열기
    self.파일열기(f'{file_path}')
  File "D:\R2A\R2A.py", line 654, in 파일열기
    self.popUp("파일 없음 : "+filePath)
TypeError: popUp() missing 1 required positional argument: 'desText'

    date=2023-11-01 12:05:56
    user=mssung
        Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 1018, in executeMultiCommand
    headerText = self.input_cmd_header.text()
AttributeError: 'WindowClass' object has no attribute 'input_cmd_header'

date=2023-11-01 12:07:19
user=mssung
    Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 1018, in executeMultiCommand
    headerText = self.input_cmd_header.text()
AttributeError: 'WindowClass' object has no attribute 'input_cmd_header'

────────────────────────────────────────date=2023-11-01 12:07:22
user=mssung
    Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 1018, in executeMultiCommand
    headerText = self.input_cmd_header.text()
AttributeError: 'WindowClass' object has no attribute 'input_cmd_header'

────────────────────────────────────────date=2023-11-01 12:34:07
user=mssung
    Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 1438, in closeEvent
    self.export_cache(isForced= True)
  File "D:\R2A\R2A.py", line 1410, in export_cache
    tempVal0 = getattr(self, f'input_findData_{i}').isChecked()
AttributeError: 'QLineEdit' object has no attribute 'isChecked'

────────────────────────────────────────
date=2023-11-01 12:34:40
user=mssung
    Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 1438, in closeEvent
    self.export_cache(isForced= True)
  File "D:\R2A\R2A.py", line 1411, in export_cache
    tempVal1 = getattr(self, f'input_findData_comment_{i}').text()
AttributeError: 'WindowClass' object has no attribute 'input_findData_comment_1'

────────────────────────────────────────
date=2023-11-01 12:36:11
user=mssung
    Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 1524, in <module>
    myWindow = WindowClass()
  File "D:\R2A\R2A.py", line 395, in __init__
    getattr(self, f'btn_findData_openFile_{i}').clicked.connect(lambda _, x=i : self.데이터파일열기(x))
AttributeError: 'WindowClass' object has no attribute 'btn_findData_openFile_4'

────────────────────────────────────────
date=2023-11-01 12:36:24
user=mssung
    Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 1524, in <module>
    myWindow = WindowClass()
  File "D:\R2A\R2A.py", line 395, in __init__
    getattr(self, f'btn_findData_openFile_{i}').clicked.connect(lambda _, x=i : self.데이터파일열기(x))
AttributeError: 'WindowClass' object has no attribute 'btn_findData_openFile_4'

────────────────────────────────────────
date=2023-11-01 12:36:30
user=mssung
    Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 1524, in <module>
    myWindow = WindowClass()
  File "D:\R2A\R2A.py", line 395, in __init__
    getattr(self, f'btn_findData_openFile_{i}').clicked.connect(lambda _, x=i : self.데이터파일열기(x))
AttributeError: 'WindowClass' object has no attribute 'btn_findData_openFile_4'

────────────────────────────────────────
date=2023-11-03 11:33:13
user=mssung
    Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 328, in <lambda>
    getattr(self, f'btn_cmd_plus_{i}').clicked.connect(lambda _, x=i : self.control_multi_cmd(x))
  File "D:\R2A\R2A.py", line 1080, in control_multi_cmd
    cur_text = total_text.splitlines()[len(total_text)-1]
IndexError: list index out of range

────────────────────────────────────────
date=2023-11-03 11:33:14
user=mssung
    Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 328, in <lambda>
    getattr(self, f'btn_cmd_plus_{i}').clicked.connect(lambda _, x=i : self.control_multi_cmd(x))
  File "D:\R2A\R2A.py", line 1080, in control_multi_cmd
    cur_text = total_text.splitlines()[len(total_text)-1]
IndexError: list index out of range

────────────────────────────────────────
date=2023-11-03 11:34:06
user=mssung
    Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 328, in <lambda>
    getattr(self, f'btn_cmd_plus_{i}').clicked.connect(lambda _, x=i : self.control_multi_cmd(x))
  File "D:\R2A\R2A.py", line 1080, in control_multi_cmd
    cur_text = total_text.splitlines()[len(total_text.splitlines())-1]
IndexError: list index out of range

────────────────────────────────────────
date=2023-11-03 11:34:13
user=mssung
    Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 328, in <lambda>
    getattr(self, f'btn_cmd_plus_{i}').clicked.connect(lambda _, x=i : self.control_multi_cmd(x))
  File "D:\R2A\R2A.py", line 1080, in control_multi_cmd
    cur_text = total_text.splitlines()[len(total_text.splitlines())-1]
IndexError: list index out of range

────────────────────────────────────────
date=2023-11-03 11:34:13
user=mssung
    Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 328, in <lambda>
    getattr(self, f'btn_cmd_plus_{i}').clicked.connect(lambda _, x=i : self.control_multi_cmd(x))
  File "D:\R2A\R2A.py", line 1080, in control_multi_cmd
    cur_text = total_text.splitlines()[len(total_text.splitlines())-1]
IndexError: list index out of range

────────────────────────────────────────
date=2023-11-06 18:34:43
user=mssung
    Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 263, in <lambda>
  File "D:\R2A\R2A.py", line 1203, in translateImg
    #self.popUp("번역",targetStr)
  File "D:\R2A\translate.py", line 11, in translateTW2KR
    result = translator.translate(targetStr,src = _srcCode, dest= _destCode)
  File "C:\Python39\lib\site-packages\googletrans\client.py", line 182, in translate
    data = self._translate(text, dest, src, kwargs)
  File "C:\Python39\lib\site-packages\googletrans\client.py", line 78, in _translate
    token = self.token_acquirer.do(text)
  File "C:\Python39\lib\site-packages\googletrans\gtoken.py", line 194, in do
    self._update()
  File "C:\Python39\lib\site-packages\googletrans\gtoken.py", line 62, in _update
    code = self.RE_TKK.search(r.text).group(1).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'

────────────────────────────────────────
date=2023-11-06 19:10:58
user=mssung
    Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 930, in changeSkillGroup
    self.input_skillGroup_level.setText(maxEnchantValue)
AttributeError: 'QSpinBox' object has no attribute 'setText'

────────────────────────────────────────
date=2023-11-06 19:12:57
user=mssung
    Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 931, in changeSkillGroup
    self.spinBox_skillGroup_level.setValue(maxEnchantValue)
TypeError: setValue(self, val: int): argument 1 has unexpected type 'str'

────────────────────────────────────────
date=2023-11-07 14:23:28
user=mssung
    Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 351, in <lambda>
    self.input_skillGroup_level.text()+" "\
AttributeError: 'WindowClass' object has no attribute 'input_skillGroup_level'

────────────────────────────────────────
date=2023-11-07 14:24:05
user=mssung
    Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 351, in <lambda>
    self.input_skillGroup_level.text()+" "\
AttributeError: 'WindowClass' object has no attribute 'input_skillGroup_level'

────────────────────────────────────────
date=2023-11-13 17:36:29
user=mssung
    Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 326, in <lambda>
    self.btn_cmd_preset_save.clicked.connect(lambda : self.make_preset('cmd'))
  File "D:\R2A\R2A.py", line 1461, in make_preset
    pm.save_preset(preset_name, df)
  File "D:\R2A\PresetManager.py", line 16, in save_preset
    dataframe.to_excel(file_path, index=False)
  File "C:\Python39\lib\site-packages\pandas\core\generic.py", line 2284, in to_excel
    formatter.write(
  File "C:\Python39\lib\site-packages\pandas\io\formats\excel.py", line 834, in write
    writer = ExcelWriter(  # type: ignore[abstract]
  File "C:\Python39\lib\site-packages\pandas\io\excel\_xlsxwriter.py", line 191, in __init__
    super().__init__(
  File "C:\Python39\lib\site-packages\pandas\io\excel\_base.py", line 925, in __init__
    self.handles = get_handle(
  File "C:\Python39\lib\site-packages\pandas\io\common.py", line 711, in get_handle
    handle = open(handle, ioargs.mode)
PermissionError: [Errno 13] Permission denied: './data/preset\\preset_item_33.xlsx'

────────────────────────────────────────
date=2023-11-13 17:52:34
user=mssung
    Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 327, in <lambda>
    self.btn_cmd_preset_load.clicked.connect(lambda : self.load_preset('cmd'))
  File "D:\R2A\R2A.py", line 1493, in load_preset
    df = df.set_index('key').T.to_dict()
  File "C:\Python39\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Python39\lib\site-packages\pandas\core\frame.py", line 5451, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['key'] are in the columns"

────────────────────────────────────────
date=2023-11-13 17:52:47
user=mssung
    Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 327, in <lambda>
    self.btn_cmd_preset_load.clicked.connect(lambda : self.load_preset('cmd'))
  File "D:\R2A\R2A.py", line 1493, in load_preset
    df = df.set_index('key').T.to_dict()
  File "C:\Python39\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Python39\lib\site-packages\pandas\core\frame.py", line 5451, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['key'] are in the columns"

────────────────────────────────────────
date=2023-11-13 18:27:11
user=mssung
    Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 324, in <lambda>
    getattr(self, f'btn_custom_execute_{i}').clicked.connect(lambda _, x=i : self.customCommand(x))
  File "D:\R2A\R2A.py", line 844, in customCommand
    count = getattr(self, f'input_custom_count_{slotNum}').text()
AttributeError: 'WindowClass' object has no attribute 'input_custom_count_1'

────────────────────────────────────────
date=2023-11-13 18:27:16
user=mssung
    Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 324, in <lambda>
    getattr(self, f'btn_custom_execute_{i}').clicked.connect(lambda _, x=i : self.customCommand(x))
  File "D:\R2A\R2A.py", line 844, in customCommand
    count = getattr(self, f'input_custom_count_{slotNum}').text()
AttributeError: 'WindowClass' object has no attribute 'input_custom_count_0'

────────────────────────────────────────
date=2023-11-13 18:28:09
user=mssung
    Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 324, in <lambda>
    getattr(self, f'btn_custom_execute_{i}').clicked.connect(lambda _, x=i : self.customCommand(x))
  File "D:\R2A\R2A.py", line 844, in customCommand
    count = getattr(self, f'input_custom_count_{slotNum}').text()
AttributeError: 'WindowClass' object has no attribute 'input_custom_count_0'

────────────────────────────────────────
date=2023-11-14 11:26:15
user=mssung
    Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 889, in addCmdPresetBookmark
    getattr(self, f'btn_cmd_preset_bookmark_{target_preset_num}').setText()
TypeError: setText(self, text: str): not enough arguments

────────────────────────────────────────
date=2023-11-14 11:26:41
user=mssung
    Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 889, in addCmdPresetBookmark
    getattr(self, f'btn_cmd_preset_bookmark_{target_preset_num}').setText()
TypeError: setText(self, text: str): not enough arguments

────────────────────────────────────────
────────────────────────────────────────
